### ISSUE TITLE
New plugin behavior for component `unmount`

### ISSUE THREAD

**Issue by dtothefp** [gaearon/react-transform-boilerplate#79] opened 2015-12-14 03:22 UTC
I have a sample component in a boilerplate repo of mine that is very similar to your counter example you have in this repo.  The only difference is I did interval logic in `componentDidMount` and I did not have a `clearInterval` in `componentWillUnmount` On previous Babel 5 version all worked fine:

```js
import React, {Component, PropTypes} from 'react';
import cx from 'classnames';
import styles from './local.css';

export default class Hello extends Component {
  static propTypes = {
    userName: PropTypes.string.isRequired
  };

  constructor(props) {
    super(props);
    this.state = {message: 'Hello'};
  }
  componentDidMount() {
    setInterval(() => {
      let message;

      if (this.state.message === 'Hello') {
        message = 'whatevss';
      } else {
        message = 'Hello';
      }

      this.setState({message});
    }, 2000);
  }
  render() {
    let classes = cx({
      'is-error': this.state.message === 'whatevss'
    });

    if (this.state.message === 'whatevss') {
      classes += ` ${styles.whatevss}`;
    } else {
      classes += ` ${styles.hello}`;
    }

    return <h1 className={classes}>{this.state.message} {this.props.userName}</h1>;
  }
}
```

Now if I use the example on new Babel 6 version and introduce a change such as `console.log` in `render` method after component has mounted I see warnings:

<img width="690" alt="screen shot 2015-12-13 at 7 19 30 pm" src="https://cloud.githubusercontent.com/assets/4656726/11772173/89e9d988-a1ce-11e5-8c64-b47d82103fb8.png">

```js
//babel-config
const babelrc = `{
  "presets": ["react", "es2015", "stage-0"],
  "env": {
    "development": {
      "plugins": [
        "rewire",
        "transform-runtime",
        "transform-decorators-legacy",
        ["react-transform",
          {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }]
      ]
    },
    "production": {
      "plugins": [
        "transform-runtime",
        "transform-decorators-legacy"
      ]
    }
  }
}`;

//webpack.config
const hmrOpts = [
  `path=${publicPath}__webpack_hmr`,
  'reload=true',
  'noInfo=true'
];
const hotEntry = [
  `webpack-hot-middleware/client?${hmrOpts.join('&')}`
];
```

**Comment by gaearon** [comment] 2015-12-24 19:57
Please link to the specific demo that reproduces it.
It's not obvious what is causing the problem.

**Comment by gaearon** [comment] 2015-12-24 21:32
I can't reproduce this with the default setup so I'm closing, as it doesn't seem to be an issue with this specific boilerplate. It might be a problem with one of the other plugins you're using, or how they work together. I'm happy to take a further look but please provide a ready runnable project because reproducing takes time.

**Closed by gaearon** 2015-12-24 21:32 UTC
