### ISSUE TITLE
Line numbers are off

### ISSUE THREAD

**Issue by mxdubois** [gaearon/react-transform-boilerplate#23] opened 2015-09-21 20:29 UTC
Hey @gaearon 

With a fresh clone of the repo, the line numbers are off. If you add `throw new Error('oops')` to line 22 of App.js (the top of the `render` function) react-redbox will display: "Counter.render \ webpack:///./src/App.js?:92:13". 

Of course, practically, it's a not a big deal because the class and method names get you pretty close, but I figure it's still worth fixing.

Thanks for setting this up!

**Comment by gaearon** [comment] 2015-09-21 21:45
Does changing `devtool: 'eval'` in `webpack.config.dev.js` to something like `devtool: 'source-map'`, `devtool: 'eval-source-map'` or `devtool: 'eval-cheap-source-map'` help? I'm starting to forget which option gives you what. I think `'eval'` is fastest, but others may give you more accurate line numbers. Let me know what you find!

**Comment by vincentfretin** [comment] 2015-09-22 07:38
Personally I use 
devtool: '#cheap-module-eval-source-map', // http://webpack.github.io/docs/configuration.html#devtool

**Comment by mxdubois** [comment] 2015-09-23 06:46
Yeah, I always get them confused too. I went ahead and tried everything:
* source-map: `"Counter.render \ http://localhost:3004/static/bundle.js:21323:14"`
* hidden-source-map: `"Counter.render \ http://localhost:3004/static/bundle.js:21323:14"`
* inline-source-map: `"Counter.render \ http://localhost:3004/static/bundle.js:21323:14"`
* cheap-source-map: `"Counter.render \ http://localhost:3004/static/bundle.js:21323:14"`
* cheap-module-source-map: `"Counter.render \ http://localhost:3004/static/bundle.js:21323:14"`
* eval: `"Counter.render \ webpack:///./src/App.js?:92:13"`
* eval-source-map**: `"Counter.render \ <anonymous>:92:13"`
* eval-cheap-source-map: `"Counter.render \ <anonymous>:92:13"`
* #cheap-module-eval-source-map: `"Counter.render \ <anonymous>:92:13"`

So, to be clear, the line numbers are always correct for the generated files available in chrome devtools but the expected behavior is to get the line numbers for the original source files. 

FWIW, when I use `eval`, `webpack:///./src/App.js` shows me generated code, whereas, when I use `source-map`, `webpack:///./src/App.js` shows me the original source code but the error logs give me `bundle.js` line numbers.

Seems like this might be related to https://github.com/jedwards1211/meteor-webpack-react/issues/40

**Comment by loudwinston** [comment] 2015-09-23 16:23
I'm seeing a similar issue.  

I can work around it by disabling `react-transform-catch-errors`.  The error then shows up in the browser console with the original filename/line number. 

With `react-transform-catch-errors` (and `react-redbox`) enabled, I only get the following

```
ReferenceError: thus is not defined
ProxyClass.render
<anonymous>:186:17
ProxyClass.proxiedMethod
<anonymous>:44:30
ProxyClass.tryRender
<anonymous>:36:31
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext
<anonymous>:789:34
ReactCompositeComponentMixin._renderValidatedComponent
<anonymous>:816:14
ReactPerf.measure.wrapper
<anonymous>:70:21
ReactCompositeComponentMixin._updateRenderedComponent
<anonymous>:746:36
ReactCompositeComponentMixin._performComponentUpdate
<anonymous>:726:10
ReactCompositeComponentMixin.updateComponent
<anonymous>:642:12
ReactPerf.measure.wrapper
<anonymous>:70:21
```

This leads me to believe that the issue is somewhere in `react-transform-catch-errors`, but that's just a guess :)

Note that I'm using `cheap-module-eval-source-map`

**Comment by loudwinston** [comment] 2015-09-23 16:46
If i use `cheap-module-eval-source-map`, all I get is something like

```
ProxyClass.render
<anonymous>:186:17
```

switching to `eval` shows
```
ProxyClass.render
webpack:///./assets/js/pages/stuff/index.js?:186:17
```

which at least shows the file, although the line number is wrong.  

However switching to `eval` means I lose source maps entirely, which is a big pain.

**Comment by pillowsoft** [comment] 2015-10-09 15:51
If you are using Chrome, you can use this: https://github.com/evanw/node-source-map-support. Use the browser version (see in the README), then use devtool: 'source-map'. The issue is that while the Chrome debugger understands source maps for stack traces, getting the stack trace through code (which is what is happening in this case), does not use them. **node-source-map-support** adds that handling, but only for Chrome (V8). Seems to work well for me (see below, all are correct line #'s, text copied from red-box output).

```
ReferenceError: cat is not defined
App.render
http://localhost:3000/webpack:/src/App.jsx:43:15
App.proxiedMethod
http://localhost:3000/webpack:/~/react-transform-hmr/~/react-proxy/modules/createPrototypeProxy.js:44:1
App.tryRender
http://localhost:3000/webpack:/~/react-transform-catch-errors/lib/index.js:36:1
[object
http://localhost:3000/webpack:/~/react/lib/ReactCompositeComponent.js:587:1
[object
http://localhost:3000/webpack:/~/react/lib/ReactCompositeComponent.js:607:1
[object
http://localhost:3000/webpack:/~/react/lib/ReactPerf.js:66:1
[object
http://localhost:3000/webpack:/~/react/lib/ReactCompositeComponent.js:220:1
[object
http://localhost:3000/webpack:/~/react/lib/ReactPerf.js:66:1
Object.ReactReconciler.mountComponent
http://localhost:3000/webpack:/~/react/lib/ReactReconciler.js:37:1
[object
http://localhost:3000/webpack:/~/react/lib/ReactCompositeComponent.js:225:1
```

**Comment by aldendaniels** [comment] 2015-10-16 16:30
@pillowsoft - This sounds right. A warning though - I used **node-source-map-support** in a project of mine and got burned badly. It's invasive because by default it tries to intercept all errors and parse out the source maps. In my case, it choked on something specific about my source  map (still not sure what) and blew up. When it blew up, it swallowed the real error and gave a very unhelpful message. It took me hours to trace the problem back to **node-source-map-support**.

My suggestion - use **node-source-map-support** to parse out source maps when catching `render()` errors, but don't install it globally.

**Comment by AoDev** [comment] 2015-10-18 18:21
Hello, I am also facing this issue. I also noted that the error layers shows the src line as links, so one expects that it will open the file (somehow, in chrome inspector or something) but it does not do anything. So, it's painful to debug currently, I always have to look for the file in the sources tab of chrome inspector.

**Comment by samiralajmovic** [comment] 2015-11-14 11:01
@gaearon tip helped me, switched from devtool: "eval" to devtool: "source-map".

**Comment by zhiqingchen** [comment] 2015-12-17 08:57
me too

**Comment by defel** [comment] 2016-02-12 10:19
Switching from 'cheap-eval-source-map' to 'source-map' results in 10 seconds more compile time, which is no option for me in dev.

**Comment by gaearon** [comment] 2016-03-06 02:02
Not sure if there’s anything actionable for us here so closing. If anyone has specific suggestions that make things better for everyone, send a PR!

**Closed by gaearon** 2016-03-06 02:02 UTC
