### ISSUE TITLE
not working in node v4?

### ISSUE THREAD

**Issue by paOol** [gaearon/react-transform-boilerplate#20] opened 2015-09-21 05:44 UTC
haven't narrowed down what the cause may be but I am on node v4.1, and npm 3.3.3.

I can see the " webpack built"  messages in terminal when I save a file, but the changes are no longer live. I have to manually F5.

**Comment by FeipingHunag** [comment] 2015-09-21 07:23
I have the same issue.

**Comment by nivoc** [comment] 2015-09-21 13:22
I've the same with node v0.10.33

**Comment by nivoc** [comment] 2015-09-21 13:54
Update: Looks like it works find with 4.0.0

**Comment by nivoc** [comment] 2015-09-21 14:20
@paOol Do you use localhost? Or do you watch with a different Machine? It works for me on localhost but not remote.

**Comment by nivoc** [comment] 2015-09-21 14:22
You can fix it if you add your IP in webpack.config@L7
For example:
    'webpack-hot-middleware/client?http://192.168.150.50:3000',

**Comment by nivoc** [comment] 2015-09-21 14:41
Update: Deleted my hint. It was wrong. It looks to me that it has something to to with remote. On localhost is works for me but on a different machine only sometimes. The "sometimes" makes it hard to find a good lead :-((

**Comment by gaearon** [comment] 2015-09-21 17:52
@nivoc

Hard to say what's wrong without a reproducing example.

**Comment by danmartinez101** [comment] 2015-09-22 00:59
Are you setting a hostname in your config? This is usually what I find I forgot when I'm having issues with my phone connecting to hot reload. But as gaearon mentioned, a repro would help us help you :D

**Comment by nivoc** [comment] 2015-09-22 05:14
@danmartinez101: The hostname was my first guess but in this case it should never work - but it works  sometimes :-(. Needle in the haystack: I tried both wildcard and specific hostname ip in the config its not the hostname.  

Repo: It happens with the unmodified clone of this repo.

@gaearon: No worries - reproducibility - working on that :-D. ...*observing*
@paOol does it fail for you all the time or as well only sometimes?

**Comment by paOol** [comment] 2015-09-22 05:32
@nivoc My setup is very close to stock. I know it stopped working (all the time) after updating my ArchLinux system and updating node and npm. 

Before that, it was working fine.

I'm going to try cloning the newer version of this boilerplate and plugging in my components over to see if the problem still persists.

**Comment by nivoc** [comment] 2015-09-30 12:49
Hmm. For me it was only happening from time to time and I tried to monitor pin it down - but now it is not happening at all anymore. I don't know. I nobody else is experience this issue I would vote for close.

**Comment by whatifif** [comment] 2015-10-01 13:50
I experienced same issue regardless to Node version on Ubuntu 14.04. 

But when I changed "http://localhost:3000" to "http://127.0.0.1:3000", it started working.

**Comment by quangbuule** [comment] 2015-10-03 00:29
@whatifif same with OSX and io.js 2.0, thanks for your hint.

**Comment by louiscntr** [comment] 2015-10-04 07:44
I think I'm having a similar issue.

First time running this boilerplate (with v4.1.1) and I couldn't for the life of me figure out why nothing was reloading correctly. Came across this issue, and then swapped over to v0.10.32. It now works a treat.

**Comment by inxilpro** [comment] 2015-10-06 00:12
I'm having the same issue. Running the unmodified version of the repo. Tried 0.10.x and 4.x versions of Node, and `localhost` and `127.0.0.1`.  This is what I see:

![Screen Shot](http://snaps.rchy.net/React_Transform_Boilerplate_2015-10-05_20-11-04.jpg)

Has anyone made any progress?

**Comment by inxilpro** [comment] 2015-10-06 00:23
I also just updated every dependency, including upgrading to React 0.14.0-rc1, tried Node v4.1.2, with same results.

**Comment by inxilpro** [comment] 2015-10-06 00:38
Gah. My issue was related to an issue with my `.babelrc` file.  Working now.

**Comment by louiscntr** [comment] 2015-10-06 01:00
@inxilpro what was the issue with the .babelrc file?

**Comment by inxilpro** [comment] 2015-10-06 01:35
It didn't have the proper setup in `extra` — see https://github.com/gaearon/react-transform-boilerplate/blob/master/.babelrc

I copied the entire contents of the repo into an existing project, and the `.babelrc` file didn't get moved over because it was hidden.

**Comment by ingro** [comment] 2015-10-10 17:19
I got the same issue, it seems related to Webpack Hot Middleware. On the browser I see that the call to http://localhost:3000/__webpack_hmr is made but gets no response, it gets canceled after ~ 20-30 seconds, and then it keep retrying with the same result.

Trying also with 127.0.0.1 but nothing changed.

**Comment by alexander-entin** [comment] 2015-12-08 12:37
could be related to #72

**Comment by manveru** [comment] 2015-12-10 10:35
Still seeing the same issue here. I can run it fine when requests come from a browser on localhost.
But once I try opening the page from another machine, it just fails to load that file for some reason.
I tried tracing the network, but there's never a response sent from express. I also added some debugging statements to the middleware that responds to `/__webpack_hmr`, and it is invoked and tries to write to the client, it's just that the headers or anything else written to that socket never make it out of node.
I'll see if i can find out more, but maybe this gives you an idea of the issue.

**Comment by gaearon** [comment] 2015-12-24 20:28
This issue has become a mix of different unrelated issues so I'll close it.

If you'd like to report a specific issue that's still active again, please do so, but with exact instructions to reproduce. If your example has any code or config changes, please publish it on GitHub as well so we can test it.

**Closed by gaearon** 2015-12-24 20:28 UTC
